// src/componentes/gameIds.js
const gameIds = {
    'red': 1,
    'blue': 2,
    'yellow': 3,
    'gold': 4,
    'silver': 5,
    'crystal': 6,
    'ruby': 7,
    'sapphire': 8,
    'emerald': 9,
    'firered': 10,
    'leafgreen': 11,
    'diamond': 12,
    'pearl': 13,
    'platinum': 14,
    'heartgold': 15,
    'soulsilver': 16,
    'black': 17,
    'white': 18,
    'colosseum': 19, 
    'xd': 20, 
    'black-2': 21,
    'white-2': 22,
    'x': 23,
    'y': 24,
    'omega-ruby': 25,
    'alpha-sapphire': 26,
    'sun': 27,
    'moon': 28,
    'ultra-sun': 29,
    'ultra-moon': 30,
    'lets-go-pikachu': 31,
    'lets-go-eevee': 32,
    'sword': 33,
    'shield': 34,
    'the-isle-of-armor': 35, 
    'the-crown-tundra': 36, 
    'brilliant-diamond': 37,
    'shining-pearl': 38,
    'legends-arceus': 39,
    'scarlet': 40,
    'violet': 41,
    'the-teal-mask': 42,
    'the-indigo-disk': 43 ,
};

export default gameIds;
